spring.application.name=dear-dev-backend
## Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=myuser
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
## Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
## Load environment specific properties
spring.config.import=optional:file:.env[.properties]

#spring.sql.init.mode=never
# disable hibernate usage of jdvc metadata
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Enable JPA Auditing
jira.api.base.url=https://dear-developer.atlassian.net
jira.api.token=MY_JIRA_API_TOKEN
