name: CI / CD

on:
  push:
    branches:
      - DEAR*
    pull_request:
      branches:
        - DEAR*

  workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2ยง

        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'adopt'

        - name: Build with Gradle
          run: ./gradlew build

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to GitHub Container Registry
          run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

        - name: Build and push Docker image
          run: |
            docker build -t ghcr.io/${{ github.repository_owner }}/dear-dev-backend:latest .
            docker push ghcr.io/${{ github.repository_owner }}/dear-dev-backend:latest